/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as CompanionsRouteImport } from './routes/companions'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as GamesRouteImport } from './routes/games'
import { Route as MapRouteImport } from './routes/map'
import { Route as NovaRouteImport } from './routes/nova'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PointsRouteImport } from './routes/points'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProtectionRouteImport } from './routes/protection'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StanRouteImport } from './routes/stan'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as CompanionsIndexRouteImport } from './routes/companions.index'
import { Route as CompanionsIdRouteImport } from './routes/companions.$id'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesIdRouteImport } from './routes/games.$id'
import { Route as TalkIdRouteImport } from './routes/talk.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionsRoute = CompanionsRouteImport.update({
  id: '/companions',
  path: '/companions',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaRoute = NovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionRoute = ProtectionRouteImport.update({
  id: '/protection',
  path: '/protection',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StanRoute = StanRouteImport.update({
  id: '/stan',
  path: '/stan',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionsIndexRoute = CompanionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanionsRoute,
} as any)
const CompanionsIdRoute = CompanionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompanionsRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GamesRoute,
} as any)
const TalkIdRoute = TalkIdRouteImport.update({
  id: '/talk/$id',
  path: '/talk/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/budget': typeof BudgetRoute
  '/companions': typeof CompanionsRouteWithChildren
  '/drive': typeof DriveRoute
  '/family': typeof FamilyRoute
  '/games': typeof GamesRouteWithChildren
  '/map': typeof MapRoute
  '/nova': typeof NovaRoute
  '/permissions': typeof PermissionsRoute
  '/plan': typeof PlanRoute
  '/planner': typeof PlannerRoute
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/protection': typeof ProtectionRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/stan': typeof StanRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/companions/$id': typeof CompanionsIdRoute
  '/games/$id': typeof GamesIdRoute
  '/talk/$id': typeof TalkIdRoute
  '/companions/': typeof CompanionsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/budget': typeof BudgetRoute
  '/drive': typeof DriveRoute
  '/family': typeof FamilyRoute
  '/map': typeof MapRoute
  '/nova': typeof NovaRoute
  '/permissions': typeof PermissionsRoute
  '/plan': typeof PlanRoute
  '/planner': typeof PlannerRoute
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/protection': typeof ProtectionRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/stan': typeof StanRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/companions/$id': typeof CompanionsIdRoute
  '/games/$id': typeof GamesIdRoute
  '/talk/$id': typeof TalkIdRoute
  '/companions': typeof CompanionsIndexRoute
  '/games': typeof GamesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/budget': typeof BudgetRoute
  '/companions': typeof CompanionsRouteWithChildren
  '/drive': typeof DriveRoute
  '/family': typeof FamilyRoute
  '/games': typeof GamesRouteWithChildren
  '/map': typeof MapRoute
  '/nova': typeof NovaRoute
  '/permissions': typeof PermissionsRoute
  '/plan': typeof PlanRoute
  '/planner': typeof PlannerRoute
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/protection': typeof ProtectionRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/stan': typeof StanRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/companions/$id': typeof CompanionsIdRoute
  '/games/$id': typeof GamesIdRoute
  '/talk/$id': typeof TalkIdRoute
  '/companions/': typeof CompanionsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/alerts'
    | '/budget'
    | '/companions'
    | '/drive'
    | '/family'
    | '/games'
    | '/map'
    | '/nova'
    | '/permissions'
    | '/plan'
    | '/planner'
    | '/points'
    | '/privacy'
    | '/protection'
    | '/routines'
    | '/settings'
    | '/stan'
    | '/stats'
    | '/terms'
    | '/api/health'
    | '/companions/$id'
    | '/games/$id'
    | '/talk/$id'
    | '/companions/'
    | '/games/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/alerts'
    | '/budget'
    | '/drive'
    | '/family'
    | '/map'
    | '/nova'
    | '/permissions'
    | '/plan'
    | '/planner'
    | '/points'
    | '/privacy'
    | '/protection'
    | '/routines'
    | '/settings'
    | '/stan'
    | '/stats'
    | '/terms'
    | '/api/health'
    | '/companions/$id'
    | '/games/$id'
    | '/talk/$id'
    | '/companions'
    | '/games'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/alerts'
    | '/budget'
    | '/companions'
    | '/drive'
    | '/family'
    | '/games'
    | '/map'
    | '/nova'
    | '/permissions'
    | '/plan'
    | '/planner'
    | '/points'
    | '/privacy'
    | '/protection'
    | '/routines'
    | '/settings'
    | '/stan'
    | '/stats'
    | '/terms'
    | '/api/health'
    | '/companions/$id'
    | '/games/$id'
    | '/talk/$id'
    | '/companions/'
    | '/games/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AlertsRoute: typeof AlertsRoute
  BudgetRoute: typeof BudgetRoute
  CompanionsRoute: typeof CompanionsRouteWithChildren
  DriveRoute: typeof DriveRoute
  FamilyRoute: typeof FamilyRoute
  GamesRoute: typeof GamesRouteWithChildren
  MapRoute: typeof MapRoute
  NovaRoute: typeof NovaRoute
  PermissionsRoute: typeof PermissionsRoute
  PlanRoute: typeof PlanRoute
  PlannerRoute: typeof PlannerRoute
  PointsRoute: typeof PointsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProtectionRoute: typeof ProtectionRoute
  RoutinesRoute: typeof RoutinesRoute
  SettingsRoute: typeof SettingsRoute
  StanRoute: typeof StanRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  TalkIdRoute: typeof TalkIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companions': {
      id: '/companions'
      path: '/companions'
      fullPath: '/companions'
      preLoaderRoute: typeof CompanionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova': {
      id: '/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof NovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection': {
      id: '/protection'
      path: '/protection'
      fullPath: '/protection'
      preLoaderRoute: typeof ProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stan': {
      id: '/stan'
      path: '/stan'
      fullPath: '/stan'
      preLoaderRoute: typeof StanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companions/': {
      id: '/companions/'
      path: '/'
      fullPath: '/companions/'
      preLoaderRoute: typeof CompanionsIndexRouteImport
      parentRoute: typeof CompanionsRoute
    }
    '/companions/$id': {
      id: '/companions/$id'
      path: '/$id'
      fullPath: '/companions/$id'
      preLoaderRoute: typeof CompanionsIdRouteImport
      parentRoute: typeof CompanionsRoute
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/talk/$id': {
      id: '/talk/$id'
      path: '/talk/$id'
      fullPath: '/talk/$id'
      preLoaderRoute: typeof TalkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompanionsRouteChildren {
  CompanionsIdRoute: typeof CompanionsIdRoute
  CompanionsIndexRoute: typeof CompanionsIndexRoute
}

const CompanionsRouteChildren: CompanionsRouteChildren = {
  CompanionsIdRoute: CompanionsIdRoute,
  CompanionsIndexRoute: CompanionsIndexRoute,
}

const CompanionsRouteWithChildren = CompanionsRoute._addFileChildren(
  CompanionsRouteChildren,
)

interface GamesRouteChildren {
  GamesIdRoute: typeof GamesIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesIdRoute: GamesIdRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AlertsRoute: AlertsRoute,
  BudgetRoute: BudgetRoute,
  CompanionsRoute: CompanionsRouteWithChildren,
  DriveRoute: DriveRoute,
  FamilyRoute: FamilyRoute,
  GamesRoute: GamesRouteWithChildren,
  MapRoute: MapRoute,
  NovaRoute: NovaRoute,
  PermissionsRoute: PermissionsRoute,
  PlanRoute: PlanRoute,
  PlannerRoute: PlannerRoute,
  PointsRoute: PointsRoute,
  PrivacyRoute: PrivacyRoute,
  ProtectionRoute: ProtectionRoute,
  RoutinesRoute: RoutinesRoute,
  SettingsRoute: SettingsRoute,
  StanRoute: StanRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  TalkIdRoute: TalkIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
